<a href="https://colab.research.google.com/github/fkhaaan/ai_foundation/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install numpy


In [7]:
import numpy as np

arr = np.array([1, 3, 7])
print('numpy_array:', arr)

arr.shape

numpy_array: [1 3 7]


(3,)

In [6]:
arr2 = np.array([[1, 3, 7, 4], [4, 6, 8, 9]])
print('numpy_array2:', arr2)
arr2.shape

numpy_array2: [[1 3 7 4]
 [4 6 8 9]]


(2, 4)

In [8]:
# dtype()
a = np.array([1, 3, 4])
print(a.dtype)

int64


In [9]:
# reshape()
a = np.array([1, 3, 4, 5, 6, 7])
b = a.reshape(2,3)
print('shaped_array:', b)

shaped_array: [[1 3 4]
 [5 6 7]]


In [10]:
# astype()
a = np.array([1, 2, 3])
b = a.astype(float)
print('float:', b)

float: [1. 2. 3.]


In [11]:
# np.zeros(), np.ones() => dummy data
z = np.zeros((2, 3))
o = np.ones((2,3))

print('zeros:', z)
print('ones:', o)

zeros: [[0. 0. 0.]
 [0. 0. 0.]]
ones: [[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
# ndim()
a = np.array([[1, 2, 3, 4], [1, 5, 6, 7]])
print('ndim:', a.ndim)

ndim: 2


In [15]:
# arange()
a = np.arange(1, 8)
print('arange:', a)

arange: [1 2 3 4 5 6 7]


In [18]:
# sum(), mean(), max(), min()

a = np.array([1, 2, 3, 4])

print('sum:', a.sum())
print('mean:', a.mean())
print('max:', a.max())
print('min:', a.min())

sum: 10
mean: 2.5
max: 4
min: 1


In [19]:
# flatten()
a = np.array([[1, 2], [3, 4]])
print('flatten:', a.flatten())

flatten: [1 2 3 4]


In [20]:
# T (Transpose)
a = np.array([[1, 2], [3, 4]])
print('transpose:', a.T)


transpose: [[1 3]
 [2 4]]


In [21]:
# dot() @
a = np.array([[ 2, 3], [ 5, 6]])
b = np.array([[ 1, 4], [ 7, 8]])
print('dot/multiplication:', a.dot(b))

dot/multiplication: [[23 32]
 [47 68]]


In [22]:
# random.rand()
a = np.random.rand(2, 3) # => 0.0 and 1.0 included , 1.0 excluded
print('random.rand:', a)

random.rand: [[0.80276466 0.62340958 0.0829323 ]
 [0.66228972 0.28943515 0.47678291]]
